#!/usr/bin/env bash
export RABBITMQ_HOST=
export RABBITMQ_PORT=5672
export RABBITMQ_USER=
export RABBITMQ_PASS=

export MYSQL_HOST=
export MYSQL_PORT=3306
export MYSQL_DB=
export MYSQL_USER=
export MYSQL_PASS=
